cards/urls.py
from django.urls import path

from .views import CardListView, CardCreateView, CardUpdateView, BoxView

app_name = "cards"

urlpatterns = [
    path("", CardListView.as_view(), name="card_list"),
    path("new", CardCreateView.as_view(), name="card_create"),
    path("edit/<int:pk>", CardUpdateView.as_view(), name="card_update"),
    path("box/<int:box_num>", BoxView.as_view(), name="box"),
]

flashcards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cards.urls", namespace="cards")),
]

cards/models.py
from django.db import models

NUM_BOXES = 5
BOXES = range(1, NUM_BOXES + 1)


class Card(models.Model):
    question = models.CharField(max_length=100)
    answer = models.CharField(max_length=100)
    box = models.IntegerField(
        choices=zip(BOXES, BOXES),
        default=BOXES[0],
    )
    date_created = models.DateTimeField(auto_now_add=True)

    def move(self, solved):
        new_box = self.box + 1 if solved else BOXES[0]

        if new_box in BOXES:
            self.box = new_box
            self.save()
        return self

    def __str__(self):
        return self.question

cards/forms.py
from django import forms


class CardCheckForm(forms.Form):
    card_id = forms.IntegerField(required=True)
    solved = forms.BooleanField(required=False)

cards/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from django.shortcuts import get_object_or_404, redirect

import random

from .models import Card
from .forms import CardCheckForm


class CardListView(ListView):
    model = Card
    queryset = Card.objects.all().order_by("box", "-date_created")
    template_name = "card_list.html"


class CardCreateView(CreateView):
    model = Card
    template_name = "card_form.html"
    fields = ["question", "answer", "box"]
    success_url = reverse_lazy("cards:card_create")


class CardUpdateView(CardCreateView, UpdateView):
    success_url = reverse_lazy("cards:card_list")


class BoxView(CardListView):
    template_name = "box.html"
    form_class = CardCheckForm

    def get_queryset(self):
        return Card.objects.filter(box=self.kwargs["box_num"])

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context["box_number"] = self.kwargs["box_num"]
        if self.object_list:
            context["check_card"] = random.choice(self.object_list)
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            card = get_object_or_404(Card, id=form.cleaned_data["card_id"])
            card.move(form.cleaned_data["solved"])
        return redirect(request.META.get("HTTP_REFERER"))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="Flashcard application">
        <title>Flashcard | {% block title %}{% endblock title %}</title>
        <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">        
    </head>
    
    <body>
        <head>
            <h1>Flashcard</h1>
            {% include "navigation.html" %}            
        </head>
        
        <main>
            <hr>
            {% block content %}
                <h2>Welcome to your Flashcard app!</h2>
            {% endblock content %}
        </main>
        
        <footer>
            <p>
                Demonstration of Flashcard application by <a href="https://realpython.com/django-flashcards-app/" target="_blank">Real Python</a> tutorial.            
            </p>
        </footer>
    </body>
</html>

templates/box.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}Boxes{% endblock title %}

{% block content %}
    <h2>🗃️ {{ box_number | ordinal }}  Box</h2>
    <mark>{{ object_list | length }} Card{{ object_list | pluralize }} left in box.</mark>
    <hr>
    {% if check_card %}
        {% include "card.html" with card=check_card %}
    {% endif %}    
{% endblock content %}

templates/box_links.html
{% load humanize %}


{% for box in boxes %}
    <a href="{% url 'cards:box' box_num=box.number %}">
        🗃️ {{ box.number | ordinal }} Box <mark>{{ box.card_count }}</mark>
    </a>
{% endfor %}

templates/card.html
<article>
    <h4>{{ card.question }}</h4>
    {% if not check_card %}
        <p>{{ card.answer }}</p>
        <hr>
        <a href="{% url 'cards:card_update' card.id %}" role="button">✏️ Edit card</a>
    {% else %}
        <details>
            <summary>Reveal Answer</summary>
            <p>{{ card.answer }}</p>
        </details>
        <hr>
        {% include "card_check_form.html" with solved=True %}
        {% include "card_check_form.html" with solved=False %}
    {% endif %}
</article>

templates/card_check_form.html
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="card_id" value="{{ card.id }}">
    <input type="hidden" name="solved" value="{{ solved }}">
    {% if solved %}
        <input type="submit" value="✅ I know">
    {% else %}
        <input type="submit" value="❌ I don't know"> 
    {% endif %}
</form>

templates/card_form.html
{% extends "base.html" %}

{% block title %}Create Card{% endblock title %}

{% block content %}    
    {% if card %}
        <h2>✏️ Edit Card</h2>
    {% else %}
        <h2>✨ Create New Card</h2>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save Card">
    </form>
    <a href="{% url 'cards:card_list' %}">Cancel</a>
{% endblock content %}

templates/card_list.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}List{% endblock title %}

{% block content %}
    <h2>
        All Cards
    </h2>
    <a href="{% url 'cards:card_create' %}" role="button">✨ Create New Card</a>
    {% for card in card_list %}
        {% ifchanged %}
            <h3>🗃️ {{ card.box| ordinal }} Box</h3>
        {% endifchanged %}        
        <article>
            {% include "card.html" %}
        </article>
    {% endfor %}
{% endblock content %}

templates/navigation.html
{% load card_tags %}

<nav>
    <a href="{% url 'cards:card_list' %}">🗃️ All Cards</a>
    {% boxes_as_links %}
</nav>